/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ws.cccm.application.model;
/**
 *
 * @author JianxinYao
 */
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;


/** 
 * Object mapping for hibernate-handled table: tblperson.
 * @author autogenerated
 */
@Entity
@Table(name="person")
public class Person extends BaseObject implements Serializable {

    /** Serial Version UID. */
    private static final long serialVersionUID = 3832626162173359488L;
    private Long 		personID;			// required
    private Long 	familyID;
    private Integer 	churchID;
    private String 		title;
    private String 		lastName;
    private String 		firstName;
    private String 		chineseName;
    private String 		gender;
    private String 		age;
    private String 		status;
    private String 		relationship;
    private String 		servingRole;
    private Boolean 	baptized;
    private Date 		baptizedDate;
    private String 		prc;
    private String 		commitServe;
    private Integer 	willingToAttendCCCM;
    private Integer 	willingToBeVoluntee;
    private Integer 	volunteerCode;
    private String 		phone;
    private String 		cellPhone;
    private String 		workPhone;
    private String 		email;
    private String 		language;
    private String 		loginID;
    private String 		password;
    private Integer 	familyAdmin;
    private Integer 	churchAdmin;
    private Integer 	searchable;
    private String 		Misc1;
    private String 		Misc2;
    private String 		Misc3;
    private Date 		lastModified;		// required
    private String 		remarks;
    private Boolean 	acceptedChrist;
    private Date 		acceptedChristDate;
    private Integer 	acceptedChristLocat;
    private Boolean 	seeker;
    private String      calling;
//    private Set<Serve> serves = new HashSet<Serve>();
    private Boolean gcSmallGroupLeader;
    private Boolean gcCoordinator;
    private Boolean gcBaptized;
    private Integer gcBaptizedSeason;
    private Boolean frInvited;
    private Boolean frTableHost;
    private Boolean stmNWU;
    private Boolean stmDekalb;
    private Boolean stmMidUSA;
    private Date stmNWUDate;
    private Date stmDekalbDate;
    private Date stmMidUSADate;
    private Boolean cmBaptized;
    private Boolean cmResponseFTServeLord;
    private Boolean cmServeLordFollowup;
    private Boolean cmResponseFTPastoral;
    private Boolean cmPastoralFollowup;
    private Boolean cmPastoralHadDevoted;
    private Boolean cmResponseFTMissionary;
    private Boolean cmMissionaryFollowup;
    private Boolean cmMissionaryHadDevoted;
    private Integer cmPastoralHadDevotedYear;
    private Integer cmMissionaryHadDevotedYear;
    private Date cmBaptizedDate;
    private Date cmPastoralFollowupDate;
    private Date cmMissionaryFollowupDate;
    private Date cmServeLordFollowupDate;
    private Date gcBaptizedDate;
    
    /**
     * Default constructor - creates a new instance with no values set.
     */
    public Person() {
    }
    /** Constructor taking a given personID.
     * @param personID to set
     */
    public Person(Long personID) {
        this.personID = personID;
    }
    /**
     * Returns the full name.
     * @return firstName + ' ' + lastName
     */
    @Transient
    public String getFullName() {
        return firstName + ' ' + lastName;
    }
    /**
     * Return the value associated with the column: Misc1.
     * @return A String object (this.Misc1)
     */
    @Column(name="Misc1",length=50)
    public String getMisc1() {
        return Misc1;
    }
    /**  
     * Set the value related to the column: Misc1.
     * @param Misc1 the Misc1 value you wish to set
     */
    public void setMisc1(String Misc1) {
        this.Misc1 = Misc1;
    }
    /**
     * Return the value associated with the column: Misc2.
     * @return A String object (this.Misc2)
     */
    @Column(name="Misc2",length=50)
    public String getMisc2() {
        return Misc2;
    }
    /**  
     * Set the value related to the column: Misc2.
     * @param Misc2 the Misc2 value you wish to set
     */
    public void setMisc2(String Misc2) {
        this.Misc2 = Misc2;
    }
    /**
     * Return the value associated with the column: Misc3.
     * @return A String object (this.Misc3)
     */
    @Column(name="Misc3",length=50)
    public String getMisc3() {
        return Misc3;
    }
    /**  
     * Set the value related to the column: Misc3.
     * @param Misc3 the Misc3 value you wish to set
     */
    public void setMisc3(String Misc3) {
        this.Misc3 = Misc3;
    }
    /**
     * Return the value associated with the column: AcceptedChrist.
     * @return A Integer object (this.acceptedChrist)
     */
    @Column(name="AcceptedChrist")
    public Boolean getAcceptedChrist() {
        return acceptedChrist;
    }
    /**  
     * Set the value related to the column: AcceptedChrist.
     * @param acceptedChrist the acceptedChrist value you wish to set
     */
    public void setAcceptedChrist(Boolean acceptedChrist) {
        this.acceptedChrist = acceptedChrist;
    }
    /**
     * Return the value associated with the column: AcceptedChristDate.
     * @return A Date object (this.acceptedChristDate)
     */
    @Column(name="AcceptedChristDate")
    @Temporal(javax.persistence.TemporalType.DATE)
    public Date getAcceptedChristDate() {
        return acceptedChristDate;
    }
    /**  
     * Set the value related to the column: AcceptedChristDate.
     * @param acceptedChristDate the acceptedChristDate value you wish to set
     */
    public void setAcceptedChristDate(Date acceptedChristDate) {
        this.acceptedChristDate = acceptedChristDate;
    }
    /**
     * Return the value associated with the column: AcceptedChristLocat.
     * @return A Integer object (this.acceptedChristLocat)
     */
    @Column(name="AcceptedChristLocat")
    public Integer getAcceptedChristLocat() {
        return acceptedChristLocat;
    }
    /**  
     * Set the value related to the column: AcceptedChristLocat.
     * @param acceptedChristLocat the acceptedChristLocat value you wish to set
     */
    public void setAcceptedChristLocat(Integer acceptedChristLocat) {
        this.acceptedChristLocat = acceptedChristLocat;
    }
    /**
     * Return the value associated with the column: Age.
     * @return A String object (this.age)
     */
    @Column(name="Age",length=5)
    public String getAge() {
        return age;
    }
    /**  
     * Set the value related to the column: Age.
     * @param age the age value you wish to set
     */
    public void setAge(String age) {
        this.age = age;
    }
    /**
     * Return the value associated with the column: Baptized.
     * @return A Integer object (this.baptized)
     */
    @Column(name="Baptized")
    public Boolean getBaptized() {
        return baptized;
    }
    /**  
     * Set the value related to the column: Baptized.
     * @param baptized the baptized value you wish to set
     */
    public void setBaptized(Boolean baptized) {
        this.baptized = baptized;
    }
     /**
     * Return the value associated with the column: BaptizedDate.
     * @return A Date object (this.baptizedDate)
     */
    @Column(name="BaptizedDate")
    public Date getBaptizedDate() {
        return baptizedDate;
    }
    /**  
     * Set the value related to the column: BaptizedDate.
     * @param baptizedDate the baptizedDate value you wish to set
     */
    public void setBaptizedDate(Date baptizedDate) {
        this.baptizedDate = baptizedDate;
    }
    /**
     * Return the value associated with the column: CellPhone.
     * @return A Double object (this.cellPhone)
     */
    @Column(name="CellPhone")
    public String getCellPhone() {
        return cellPhone;
    }
    /**  
     * Set the value related to the column: CellPhone.
     * @param cellPhone the cellPhone value you wish to set
     */
    public void setCellPhone(String cellPhone) {
        this.cellPhone = cellPhone;
    }
    /**
     * Return the value associated with the column: ChineseName.
     * @return A String object (this.chineseName)
     */
    @Column(name="ChineseName",length = 50)
    public String getChineseName() {
        return chineseName;
    }
    /**  
     * Set the value related to the column: ChineseName.
     * @param chineseName the chineseName value you wish to set
     */
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }
    /**
     * Return the value associated with the column: ChurchAdmin.
     * @return A Integer object (this.churchAdmin)
     */
    @Column(name="ChurchAdmin")
    public Integer getChurchAdmin() {
        return churchAdmin;
    }
     /**  
     * Set the value related to the column: ChurchAdmin.
     * @param churchAdmin the churchAdmin value you wish to set
     */
    public void setChurchAdmin(Integer churchAdmin) {
        this.churchAdmin = churchAdmin;
    }
    /**
     * Return the value associated with the column: ChurchID.
     * @return A Integer object (this.churchID)
     */
    @Column(name="ChurchID")
    public Integer getChurchID() {
        return churchID;
    }
    /**  
     * Set the value related to the column: ChurchID.
     * @param churchID the churchID value you wish to set
     */
    public void setChurchID(Integer churchID) {
        this.churchID = churchID;
    }
    /**
     * Return the value associated with the column: CommitServe.
     * @return A String object (this.commitServe)
     */
    @Column(name="CommitServe",length = 50)
    public String getCommitServe() {
        return commitServe;
    }
     /**  
     * Set the value related to the column: CommitServe.
     * @param commitServe the commitServe value you wish to set
     */
    public void setCommitServe(String commitServe) {
        this.commitServe = commitServe;
    }
    /**
     * Return the value associated with the column: Email.
     * @return A String object (this.email)
     */
    @Column(name="Email",length = 50)
    public String getEmail() {
        return email;
    }
    /**  
     * Set the value related to the column: Email.
     * @param email the email value you wish to set
     */
    public void setEmail(String email) {
        this.email = email;
    }
     /**
     * Return the value associated with the column: FamilyAdmin.
     * @return A Integer object (this.familyAdmin)
     */
    @Column(name="FamilyAdmin")
    public Integer getFamilyAdmin() {
        return familyAdmin;
    }
     /**  
     * Set the value related to the column: FamilyAdmin.
     * @param familyAdmin the familyAdmin value you wish to set
     */
    public void setFamilyAdmin(Integer familyAdmin) {
        this.familyAdmin = familyAdmin;
    }
    /**
     * Return the value associated with the column: FamilyID.
     * @return A Integer object (this.familyID)
     */
    @Column(name="FamilyID")
    public Long getFamilyID() {
        return familyID;
    }
    /**  
     * Set the value related to the column: FamilyID.
     * @param familyID the familyID value you wish to set
     */
    public void setFamilyID(Long familyID) {
        this.familyID = familyID;
    }
     /**
     * Return the value associated with the column: FirstName.
     * @return A String object (this.firstName)
     */
   @Column(name="FirstName",length = 20)
    public String getFirstName() {
        return firstName;
    }
    /**  
     * Set the value related to the column: FirstName.
     * @param firstName the firstName value you wish to set
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    /**
     * Return the value associated with the column: Gender.
     * @return A String object (this.gender)
     */
    @Column(name="Gender",length = 2)
    public String getGender() {
        return gender;
    }
    /**
     * Set the value related to the column: Gender.
     * @param gender the gender value you wish to set
     */
    public void setGender(String gender) {
        this.gender = gender;
    }
     /**
     * Return the value associated with the column: Language.
     * @return A String object (this.language)
     */
    @Column(name="Language",length = 50)
    public String getLanguage() {
        return language;
    }
    /**
     * Set the value related to the column: Language.
     * @param language the language value you wish to set
     */
    public void setLanguage(String language) {
        this.language = language;
    }
    /**
     * Return the value associated with the column: LastModified.
     * @return A Date object (this.lastModified)
     */
    @Column(name = "LastModified", nullable = false)
    public Date getLastModified() {
        return lastModified=new Date();
    }
     /**
     * Set the value related to the column: LastModified.
     * @param lastModified the lastModified value you wish to set
     */
    public void setLastModified(Date lastModified) {
        
        this.lastModified = lastModified;
    }
    /**
     * Return the value associated with the column: LastName.
     * @return A String object (this.lastName)
     */
    @Column(name = "LastName",length = 20)
    public String getLastName() {
        return lastName;
    }
    /**
     * Set the value related to the column: LastName.
     * @param lastName the lastName value you wish to set
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    /**
     * Return the value associated with the column: LoginID.
     * @return A String object (this.loginID)
     */
    @Column(name = "LoginID",length = 50)
    public String getLoginID() {
        return loginID;
    }
    /**
     * Set the value related to the column: LoginID.
     * @param loginID the loginID value you wish to set
     */
    public void setLoginID(String loginID) {
        this.loginID = loginID;
    }
     /**
     * Return the value associated with the column: Password.
     * @return A String object (this.password)
     */
    @Column(name = "Password",length = 50)
    public String getPassword() {
        return password;
    }
    /**
     * Set the value related to the column: Password.
     * @param password the password value you wish to set
     */
    public void setPassword(String password) {
        this.password = password;
    }
    /**
     * Return the value associated with the column: PersonID.
     * @return A Long object (this.personID)
     */
    @Id
    @Column(name = "PersonID", nullable = false)
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getPersonID() {
        return personID;
    }
    /**
     * Set the value related to the column: PersonID.
     * @param personID the personID value you wish to set
     */
    public void setPersonID(Long personID) {
        this.personID = personID;
    }
    /**
     * Return the value associated with the column: Phone.
     * @return A String object (this.phone)
     */
    @Column(name = "Phone",length = 15)
    public String getPhone() {
        return phone;
    }
     /**
     * Set the value related to the column: Phone.
     * @param phone the phone value you wish to set
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
    /**
     * Return the value associated with the column: PRC.
     * @return A String object (this.prc)
     */
    @Column(name = "PRC",length = 50)
    public String getPrc() {
        return prc;
    }
    /**
     * Set the value related to the column: PRC.
     * @param prc the prc value you wish to set
     */
    public void setPrc(String prc) {
        this.prc = prc;
    }
    /**
     * Return the value associated with the column: Relationship.
     * @return A String object (this.relationship)
     */
     @Column(name = "Relationship",length = 2)
    public String getRelationship() {
        return relationship;
    }
    /**
     * Set the value related to the column: Relationship.
     * @param relationship the relationship value you wish to set
     */
    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }
    /**
     * Return the value associated with the column: Remarks.
     * @return A String object (this.remarks)
     */
    @Column(name = "Remarks",length = 255)
    public String getRemarks() {
        return remarks;
    }
    /**
     * Set the value related to the column: Remarks.
     * @param remarks the remarks value you wish to set
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    /**
     * Return the value associated with the column: Searchable.
     * @return A Integer object (this.searchable)
     */
    @Column(name = "Searchable")
    public Integer getSearchable() {
        return searchable;
    }
    /**
     * Set the value related to the column: Searchable.
     * @param searchable the searchable value you wish to set
     */
    public void setSearchable(Integer searchable) {
        this.searchable = searchable;
    }
    /**
     * Return the value associated with the column: Seeker.
     * @return A Integer object (this.seeker)
     */
    @Column(name = "Seeker")
    public Boolean getSeeker() {
        return seeker;
    }
    /**
     * Set the value related to the column: Seeker.
     * @param seeker the seeker value you wish to set
     */
    public void setSeeker(Boolean seeker) {
        this.seeker = seeker;
    }
    /**
     * Return the value associated with the column: ServingRole.
     * @return A String object (this.servingRole)
     */
    @Column(name = "ServingRole",length = 50)
    public String getServingRole() {
        return servingRole;
    }
    /**
     * Set the value related to the column: ServingRole.
     * @param servingRole the servingRole value you wish to set
     */
    public void setServingRole(String servingRole) {
        this.servingRole = servingRole;
    }
     /**
     * Return the value associated with the column: Status.
     * @return A String object (this.status)
     */
    @Column(name = "Status",length = 2)
    public String getStatus() {
        return status;
    }
    /**
     * Set the value related to the column: Status.
     * @param status the status value you wish to set
     */
    public void setStatus(String status) {
        this.status = status;
    }
    /**
     * Return the value associated with the column: Title.
     * @return A String object (this.title)
     */
    @Column(name = "Title",length = 50)
    public String getTitle() {
        return title;
    }
    /**
     * Set the value related to the column: Title.
     * @param title the title value you wish to set
     */
    public void setTitle(String title) {
        this.title = title;
    }
    /**
     * Return the value associated with the column: VolunteerCode.
     * @return A Integer object (this.volunteerCode)
     */
    @Column(name = "VolunteerCode")
    public Integer getVolunteerCode() {
        return volunteerCode;
    }
    /**
     * Set the value related to the column: VolunteerCode.
     * @param volunteerCode the volunteerCode value you wish to set
     */
    public void setVolunteerCode(Integer volunteerCode) {
        this.volunteerCode = volunteerCode;
    }
    /**
     * Return the value associated with the column: WillingToAttendCCCM.
     * @return A Integer object (this.willingToAttendCCCM)
     */
    @Column(name = "WillingToAttendCCCM")
    public Integer getWillingToAttendCCCM() {
        return willingToAttendCCCM;
    }
    /**
     * Set the value related to the column: WillingToAttendCCCM.
     * @param willingToAttendCCCM the willingToAttendCCCM value you wish to set
     */
    public void setWillingToAttendCCCM(Integer willingToAttendCCCM) {
        this.willingToAttendCCCM = willingToAttendCCCM;
    }
    /**
     * Return the value associated with the column: WillingToBeVoluntee.
     * @return A Integer object (this.willingToBeVoluntee)
     */
    @Column(name = "WillingToBeVoluntee")
    public Integer getWillingToBeVoluntee() {
        return willingToBeVoluntee;
    }
    /**
     * Set the value related to the column: WillingToBeVoluntee.
     * @param willingToBeVoluntee the willingToBeVoluntee value you wish to set
     */
    public void setWillingToBeVoluntee(Integer willingToBeVoluntee) {
        this.willingToBeVoluntee = willingToBeVoluntee;
    }
    /**
     * Return the value associated with the column: WorkPhone.
     * @return A Double object (this.workPhone)
     */
    @Column(name = "WorkPhone")
    public String getWorkPhone() {
        return workPhone;
    }
    /**
     * Set the value related to the column: WorkPhone.
     * @param workPhone the workPhone value you wish to set
     */
    public void setWorkPhone(String workPhone) {
        this.workPhone = workPhone;
    }

    /**
     * Return the value associated with the column: calling.
     * @return A String object (this.calling)
     */
    @Column(name = "calling")
    public String getCalling() {
        return calling;
    }
    /**
     * Set the value related to the column: calling.
     * @param calling the calling value you wish to set
     */
    public void setCalling(String calling) {
        this.calling = calling;
    }

//    @ManyToMany(fetch = FetchType.EAGER)
//    @JoinTable(
//            name="person_serve",
//            joinColumns = { @JoinColumn( name="personID") },
//            inverseJoinColumns = @JoinColumn( name="serveID")
//    )
//    public Set<Serve> getServes() {
//        return serves;
//    }
//
//    public void setServes(Set<Serve> serves) {
//        this.serves = serves;
//    }
//
//    /**
//     * Convert user roles to LabelValue objects for convenience.
//     * @return a list of LabelValue objects with role information
//     */
//    @Transient
//    public Map<Long, String> getServeMap() {
//        Map<Long, String> serveMap= new HashMap<Long, String>();
//
//        if (this.serves != null) {
//            for (Serve serve : serves) {
//                // convert the user's roles to LabelValue Objects
//                serveMap.put(serve.getServeID(), serve.getName());
//            }
//        }
//
//        return serveMap;
//    }

    /**
     * Return the value associated with the column: frInvited.
     * @return A String object (this.frInvited)
     */
    @Column(name = "frInvited")
    public Boolean getFrInvited() {
        return frInvited;
    }

    /**
     * Set the value related to the column: frInvited.
     * @param calling the calling value you wish to set
     */
    public void setFrInvited(Boolean frInvited) {
        this.frInvited = frInvited;
    }

    /**
     * Return the value associated with the column: frTableHost.
     * @return A String object (this.frTableHost)
     */
    @Column(name = "frTableHost")
    public Boolean getFrTableHost() {
        return frTableHost;
    }

    /**
     * Set the value related to the column: frTableHost.
     * @param calling the calling value you wish to set
     */
    public void setFrTableHost(Boolean frTableHost) {
        this.frTableHost = frTableHost;
    }

    /**
     * Return the value associated with the column: gcBaptized.
     * @return A String object (this.gcBaptized)
     */
    @Column(name = "gcBaptized")
    public Boolean getGcBaptized() {
        return gcBaptized;
    }

    /**
     * Set the value related to the column: gcBaptized.
     * @param calling the calling value you wish to set
     */
    public void setGcBaptized(Boolean gcBaptized) {
        this.gcBaptized = gcBaptized;
    }

    /**
     * Return the value associated with the column: gcBaptizedSeason.
     * @return A String object (this.gcBaptizedSeason)
     */
    @Column(name = "gcBaptizedSeason")
    public Integer getGcBaptizedSeason() {
        return gcBaptizedSeason;
    }

    /**
     * Set the value related to the column: gcBaptizedSeason.
     * @param calling the calling value you wish to set
     */
    public void setGcBaptizedSeason(Integer gcBaptizedSeason) {
        this.gcBaptizedSeason = gcBaptizedSeason;
    }

    /**
     * Return the value associated with the column: gcCoordinator.
     * @return A String object (this.gcCoordinator)
     */
    @Column(name = "gcCoordinator")
    public Boolean getGcCoordinator() {
        return gcCoordinator;
    }

    /**
     * Set the value related to the column: gcCoordinator.
     * @param calling the calling value you wish to set
     */
    public void setGcCoordinator(Boolean gcCoordinator) {
        this.gcCoordinator = gcCoordinator;
    }

    /**
     * Return the value associated with the column: gcSmallGroupLeader.
     * @return A String object (this.gcSmallGroupLeader)
     */
    @Column(name = "gcSmallGroupLeader")
    public Boolean getGcSmallGroupLeader() {
        return gcSmallGroupLeader;
    }

    /**
     * Set the value related to the column: gcSmallGroupLeader.
     * @param calling the calling value you wish to set
     */
    public void setGcSmallGroupLeader(Boolean gcSmallGroupLeader) {
        this.gcSmallGroupLeader = gcSmallGroupLeader;
    }

    /**
     * Return the value associated with the column: stmDekalb.
     * @return A String object (this.stmDekalb)
     */
    @Column(name = "stmDekalb")
    public Boolean getStmDekalb() {
        return stmDekalb;
    }

    /**
     * Set the value related to the column: stmDekalb.
     * @param calling the calling value you wish to set
     */
    public void setStmDekalb(Boolean stmDekalb) {
        this.stmDekalb = stmDekalb;
    }

    /**
     * Return the value associated with the column: stmDekalbDate.
     * @return A String object (this.stmDekalbDate)
     */
    @Column(name = "stmDekalbDate")
    @Temporal(javax.persistence.TemporalType.DATE)
    public Date getStmDekalbDate() {
        return stmDekalbDate;
    }

    /**
     * Set the value related to the column: stmDekalbDate.
     * @param calling the calling value you wish to set
     */
    public void setStmDekalbDate(Date stmDekalbDate) {
        this.stmDekalbDate = stmDekalbDate;
    }

    /**
     * Return the value associated with the column: stmMidUSA.
     * @return A String object (this.stmMidUSA)
     */
    @Column(name = "stmMidUSA")
    public Boolean getStmMidUSA() {
        return stmMidUSA;
    }

    /**
     * Set the value related to the column: stmMidUSA.
     * @param calling the calling value you wish to set
     */
    public void setStmMidUSA(Boolean stmMidUSA) {
        this.stmMidUSA = stmMidUSA;
    }

    /**
     * Return the value associated with the column: stmMidUSADate.
     * @return A String object (this.stmMidUSADate)
     */
    @Column(name = "stmMidUSADate")
    public Date getStmMidUSADate() {
        return stmMidUSADate;
    }

    /**
     * Set the value related to the column: stmMidUSADate.
     * @param calling the calling value you wish to set
     */
    public void setStmMidUSADate(Date stmMidUSADate) {
        this.stmMidUSADate = stmMidUSADate;
    }

    /**
     * Return the value associated with the column: stmNWU.
     * @return A String object (this.stmNWU)
     */
    @Column(name = "stmNWU")
    public Boolean getStmNWU() {
        return stmNWU;
    }

    /**
     * Set the value related to the column: stmNWU.
     * @param calling the calling value you wish to set
     */
    public void setStmNWU(Boolean stmNWU) {
        this.stmNWU = stmNWU;
    }

    /**
     * Return the value associated with the column: stmNWUDate.
     * @return A String object (this.stmNWUDate)
     */
    @Column(name = "stmNWUDate")
    public Date getStmNWUDate() {
        return stmNWUDate;
    }
    /**
     * Set the value related to the column: stmNWUDate.
     * @param calling the calling value you wish to set
     */
    public void setStmNWUDate(Date stmNWUDate) {
        this.stmNWUDate = stmNWUDate;
    }
    /**
     * Return the value associated with the column: cmBaptized.
     * @return A String object (this.cmBaptized)
     */
    @Column(name = "cmBaptized")
    public Boolean getCmBaptized() {
        return cmBaptized;
    }
    /**
     * Set the value related to the column: cmBaptized.
     * @param calling the calling value you wish to set
     */
    public void setCmBaptized(Boolean cmBaptized) {
        this.cmBaptized = cmBaptized;
    }
    /**
     * Return the value associated with the column: cmMissionaryFollowup.
     * @return A String object (this.cmMissionaryFollowup)
     */
    @Column(name = "cmMissionaryFollowup")
    public Boolean getCmMissionaryFollowup() {
        return cmMissionaryFollowup;
    }
    /**
     * Set the value related to the column: cmMissionaryFollowup.
     * @param calling the calling value you wish to set
     */
    public void setCmMissionaryFollowup(Boolean cmMissionaryFollowup) {
        this.cmMissionaryFollowup = cmMissionaryFollowup;
    }
    /**
     * Return the value associated with the column: cmMissionaryFollowupDate.
     * @return A String object (this.cmMissionaryFollowupDate)
     */
    @Column(name = "cmMissionaryFollowupDate")
    public Date getCmMissionaryFollowupDate() {
        return cmMissionaryFollowupDate;
    }
    /**
     * Set the value related to the column: cmMissionaryFollowupDate.
     * @param calling the calling value you wish to set
     */
    public void setCmMissionaryFollowupDate(Date cmMissionaryFollowupDate) {
        this.cmMissionaryFollowupDate = cmMissionaryFollowupDate;
    }
    /**
     * Return the value associated with the column: cmMissionaryHadDevoted.
     * @return A String object (this.cmMissionaryHadDevoted)
     */
    @Column(name = "cmMissionaryHadDevoted")
    public Boolean getCmMissionaryHadDevoted() {
        return cmMissionaryHadDevoted;
    }
    /**
     * Set the value related to the column: cmMissionaryHadDevoted.
     * @param calling the calling value you wish to set
     */
    public void setCmMissionaryHadDevoted(Boolean cmMissionaryHadDevoted) {
        this.cmMissionaryHadDevoted = cmMissionaryHadDevoted;
    }
    /**
     * Return the value associated with the column: cmMissionaryHadDevotedYear.
     * @return A String object (this.cmMissionaryHadDevotedYear)
     */
    @Column(name = "cmMissionaryHadDevotedYear")
    public Integer getCmMissionaryHadDevotedYear() {
        return cmMissionaryHadDevotedYear;
    }
    /**
     * Set the value related to the column: cmMissionaryHadDevotedYear.
     * @param calling the calling value you wish to set
     */
    public void setCmMissionaryHadDevotedYear(Integer cmMissionaryHadDevotedYear) {
        this.cmMissionaryHadDevotedYear = cmMissionaryHadDevotedYear;
    }
    /**
     * Return the value associated with the column: cmPastoralFollowup.
     * @return A String object (this.cmPastoralFollowup)
     */
    @Column(name = "cmPastoralFollowup")
    public Boolean getCmPastoralFollowup() {
        return cmPastoralFollowup;
    }
    /**
     * Set the value related to the column: cmPastoralFollowup.
     * @param calling the calling value you wish to set
     */
    public void setCmPastoralFollowup(Boolean cmPastoralFollowup) {
        this.cmPastoralFollowup = cmPastoralFollowup;
    }
    /**
     * Return the value associated with the column: cmPastoralFollowupDate.
     * @return A String object (this.cmPastoralFollowupDate)
     */
    @Column(name = "cmPastoralFollowupDate")
    public Date getCmPastoralFollowupDate() {
        return cmPastoralFollowupDate;
    }
    /**
     * Set the value related to the column: cmPastoralFollowupDate.
     * @param calling the calling value you wish to set
     */
    public void setCmPastoralFollowupDate(Date cmPastoralFollowupDate) {
        this.cmPastoralFollowupDate = cmPastoralFollowupDate;
    }
    /**
     * Return the value associated with the column: cmPastoralHadDevoted.
     * @return A String object (this.cmPastoralHadDevoted)
     */
    @Column(name = "cmPastoralHadDevoted")
    public Boolean getCmPastoralHadDevoted() {
        return cmPastoralHadDevoted;
    }
    /**
     * Set the value related to the column: cmPastoralHadDevoted.
     * @param calling the calling value you wish to set
     */
    public void setCmPastoralHadDevoted(Boolean cmPastoralHadDevoted) {
        this.cmPastoralHadDevoted = cmPastoralHadDevoted;
    }
    /**
     * Return the value associated with the column: cmPastoralHadDevotedYear.
     * @return A String object (this.cmPastoralHadDevotedYear)
     */
    @Column(name = "cmPastoralHadDevotedYear")
    public Integer getCmPastoralHadDevotedYear() {
        return cmPastoralHadDevotedYear;
    }
    /**
     * Set the value related to the column: cmPastoralHadDevotedYear.
     * @param calling the calling value you wish to set
     */
    public void setCmPastoralHadDevotedYear(Integer cmPastoralHadDevotedYear) {
        this.cmPastoralHadDevotedYear = cmPastoralHadDevotedYear;
    }
    /**
     * Return the value associated with the column: cmResponseFTMissionary.
     * @return A String object (this.cmResponseFTMissionary)
     */
    @Column(name = "cmResponseFTMissionary")
    public Boolean getCmResponseFTMissionary() {
        return cmResponseFTMissionary;
    }
    /**
     * Set the value related to the column: cmResponseFTMissionary.
     * @param calling the calling value you wish to set
     */
    public void setCmResponseFTMissionary(Boolean cmResponseFTMissionary) {
        this.cmResponseFTMissionary = cmResponseFTMissionary;
    }
    /**
     * Return the value associated with the column: cmResponseFTPastoral.
     * @return A String object (this.cmResponseFTPastoral)
     */
    @Column(name = "cmResponseFTPastoral")
    public Boolean getCmResponseFTPastoral() {
        return cmResponseFTPastoral;
    }
    /**
     * Set the value related to the column: cmResponseFTPastoral.
     * @param calling the calling value you wish to set
     */
    public void setCmResponseFTPastoral(Boolean cmResponseFTPastoral) {
        this.cmResponseFTPastoral = cmResponseFTPastoral;
    }
    /**
     * Return the value associated with the column: cmResponseFTServeLord.
     * @return A String object (this.cmResponseFTServeLord)
     */
    @Column(name = "cmResponseFTServeLord")
    public Boolean getCmResponseFTServeLord() {
        return cmResponseFTServeLord;
    }
    /**
     * Set the value related to the column: cmResponseFTServeLord.
     * @param calling the calling value you wish to set
     */
    public void setCmResponseFTServeLord(Boolean cmResponseFTServeLord) {
        this.cmResponseFTServeLord = cmResponseFTServeLord;
    }
    /**
     * Return the value associated with the column: cmServeLordFollowup.
     * @return A String object (this.cmResponseFTServeLord)
     */
    @Column(name = "cmServeLordFollowup")
    public Boolean getCmServeLordFollowup() {
        return cmServeLordFollowup;
    }
    /**
     * Set the value related to the column: cmResponseFTServeLord.
     * @param calling the calling value you wish to set
     */
    public void setCmServeLordFollowup(Boolean cmServeLordFollowup) {
        this.cmServeLordFollowup = cmServeLordFollowup;
    }
    /**
     * Return the value associated with the column: cmServeLordFollowupDate.
     * @return A String object (this.cmServeLordFollowupDate)
     */
    @Column(name = "cmServeLordFollowupDate")
    public Date getCmServeLordFollowupDate() {
        return cmServeLordFollowupDate;
    }
    /**
     * Set the value related to the column: cmServeLordFollowupDate.
     * @param calling the calling value you wish to set
     */
    public void setCmServeLordFollowupDate(Date cmServeLordFollowupDate) {
        this.cmServeLordFollowupDate = cmServeLordFollowupDate;
    }
    /**
     * Return the value associated with the column: cmBaptizedDate.
     * @return A String object (this.cmBaptizedDate)
     */
    @Column(name = "cmBaptizedDate")
    public Date getCmBaptizedDate() {
        return cmBaptizedDate;
    }
    /**
     * Set the value related to the column: cmBaptizedDate.
     * @param calling the calling value you wish to set
     */
    public void setCmBaptizedDate(Date cmBaptizedDate) {
        this.cmBaptizedDate = cmBaptizedDate;
    }
    /**
     * Return the value associated with the column: gcBaptizedDate.
     * @return A String object (this.gcBaptizedDate)
     */
    @Column(name = "gcBaptizedDate")
    public Date getGcBaptizedDate() {
        return gcBaptizedDate;
    }
    /**
     * Set the value related to the column: gcBaptizedDate.
     * @param calling the calling value you wish to set
     */
    public void setGcBaptizedDate(Date gcBaptizedDate) {
        this.gcBaptizedDate = gcBaptizedDate;
    }
    /**
     * {@inheritDoc}
     */
    public int hashCode() {
        int result = 0;
        result =
                1000008 * result + (this.age == null ? 0 : this.age.hashCode());
        result =
                1000008 * result + (this.chineseName == null ? 0 : this.chineseName.hashCode());
        result =
                1000008 * result + (this.email == null ? 0 : this.email.hashCode());
        result =
                1000008 * result + (this.firstName == null ? 0 : this.firstName.hashCode());
        result =
                1000008 * result + (this.gender == null ? 0 : this.gender.hashCode());
        result =
                1000008 * result + (this.personID == null ? 0 : this.personID.hashCode());
        result =
                1000008 * result + (this.lastName == null ? 0 : this.lastName.hashCode());
        result =
                1000008 * result + (this.relationship == null ? 0 : this.relationship.hashCode());
        result =
                1000008 * result + (this.remarks == null ? 0 : this.remarks.hashCode());
        

        result =
                1000008 * result + (this.status == null ? 0 : this.status.hashCode());


        result = 1000008 * result + (this.churchID == null ? 0 : this.churchID.hashCode());
        result = 1000008 * result + (this.familyID == null ? 0 : this.familyID.hashCode());
        result = 1000008 * result + (this.title == null ? 0 : this.title.hashCode());
        result = 1000008 * result + (this.servingRole == null ? 0 : this.servingRole.hashCode());
        
        result = 1000008 * result + (this.baptizedDate == null ? 0 : this.baptizedDate.hashCode());
        result = 1000008 * result + (this.prc == null ? 0 : this.prc.hashCode());
        result = 1000008 * result + (this.commitServe == null ? 0 : this.commitServe.hashCode());
        result = 1000008 * result + (this.willingToAttendCCCM == null ? 0 : this.willingToAttendCCCM.hashCode());
        result = 1000008 * result + (this.willingToBeVoluntee == null ? 0 : this.willingToBeVoluntee.hashCode());
        result = 1000008 * result + (this.volunteerCode == null ? 0 : this.willingToBeVoluntee.hashCode());
        result = 1000008 * result + (this.phone == null ? 0 : this.phone.hashCode());
        result = 1000008 * result + (this.cellPhone == null ? 0 : this.cellPhone.hashCode());
        result = 1000008 * result + (this.workPhone == null ? 0 : this.workPhone.hashCode());
        result = 1000008 * result + (this.language == null ? 0 : this.language.hashCode());
        result = 1000008 * result + (this.loginID == null ? 0 : this.loginID.hashCode());
        result = 1000008 * result + (this.password == null ? 0 : this.password.hashCode());
        result = 1000008 * result + (this.familyAdmin == null ? 0 : this.familyAdmin.hashCode());
        result = 1000008 * result + (this.churchAdmin == null ? 0 : this.churchAdmin.hashCode());
        result = 1000008 * result + (this.searchable == null ? 0 : this.searchable.hashCode());
        result = 1000008 * result + (this.Misc1 == null ? 0 : this.Misc1.hashCode());
        result = 1000008 * result + (this.Misc2 == null ? 0 : this.Misc2.hashCode());
        result = 1000008 * result + (this.Misc3 == null ? 0 : this.Misc3.hashCode());
        result = 1000008 * result + (this.lastModified == null ? 0 : this.lastModified.hashCode());
        result = 1000008 * result + (this.acceptedChrist == null ? 0 : this.acceptedChrist.hashCode());
        result = 1000008 * result + (this.acceptedChristDate == null ? 0 : this.acceptedChristDate.hashCode());
        result = 1000008 * result + (this.acceptedChristLocat == null ? 0 : this.acceptedChristLocat.hashCode());
        return result;
    }

    /**
     * {@inheritDoc}
     */
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Person)) {
            return false;
        }

        final Person person = (Person) o;

        return !(chineseName != null ? !chineseName.equals(person.getChineseName()) :person.getChineseName() != null);
    }
     /**
      * {@inheritDoc}
      */
    public String toString(){
        StringBuffer sb = new StringBuffer();

        sb.append("personID: " + this.personID + ", ");
        sb.append("familyID: " + this.familyID + ", ");
        sb.append("churchID: " + this.churchID + ", ");
        sb.append("title: " + this.title + ", ");
        sb.append("lastName: " + this.lastName + ", ");
        sb.append("firstName: " + this.firstName + ", ");
        sb.append("chineseName: " + this.chineseName + ", ");
        sb.append("gender: " + this.gender + ", ");
        sb.append("age: " + this.age + ", ");
        sb.append("status: " + this.status + ", ");
        sb.append("relationship: " + this.relationship + ", ");
        sb.append("servingRole: " + this.servingRole + ", ");
        sb.append("baptized: " + this.baptized + ", ");
        sb.append("baptizedDate: " + this.baptizedDate + ", ");
        sb.append("prc: " + this.prc + ", ");
        sb.append("commitServe: " + this.commitServe + ", ");
        sb.append("willingToAttendCCCM: " + this.willingToAttendCCCM + ", ");
        sb.append("willingToBeVoluntee: " + this.willingToBeVoluntee + ", ");
        sb.append("volunteerCode: " + this.volunteerCode + ", ");
        sb.append("phone: " + this.phone + ", ");
        sb.append("cellPhone: " + this.cellPhone + ", ");
        sb.append("workPhone: " + this.workPhone + ", ");
        sb.append("email: " + this.email + ", ");
        sb.append("language: " + this.language + ", ");
        sb.append("loginID: " + this.loginID + ", ");
        sb.append("password: " + this.password + ", ");
        sb.append("familyAdmin: " + this.familyAdmin + ", ");
        sb.append("churchAdmin: " + this.churchAdmin + ", ");
        sb.append("searchable: " + this.searchable + ", ");
        sb.append("Misc1: " + this.Misc1 + ", ");
        sb.append("Misc2: " + this.Misc2 + ", ");
        sb.append("Misc3: " + this.Misc3 + ", ");
        sb.append("lastModified: " + this.lastModified + ", ");
        sb.append("remarks: " + this.remarks + ", ");
        sb.append("acceptedChrist: " + this.acceptedChrist + ", ");
        sb.append("acceptedChristDate: " + this.acceptedChristDate + ", ");
        sb.append("acceptedChristLocat: " + this.acceptedChristLocat + ", ");
        sb.append("seeker: " + this.seeker + ", ");
        return sb.toString();
    }    
}
