package com.cclife.registration.domain;

import java.io.Serializable;

public enum Server implements Serializable {
    SMALL_GROUP_LEADER, HOSPITALITY, AUDIO_VISUAL, TRANSPORTATION, PRAYER_TEAM, NURSERY_HELPER, USHERS, WORKSHOP_COORDINATOR, FOOD_SERVICE, MEDICAL_SUPPORT, REGISTRATION, INTERPRETER, FOLLOWUP, OTHER;
}
